name: C Project Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    # Install any dependencies your project needs
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    # Build the project
    - name: Build
      run: make

    # Run the tests and allow failure
    - name: Run tests
      continue-on-error: false  # This will make the workflow fail if tests fail
      run: |
        make test
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          echo "::error::Tests failed with exit code $exit_code"
        fi